export interface MisMetricas {
  id_persona: string,
  peso: string,
  altura: string,
  edad: string,
  objetivo: string,
  consecutivo: string,
  grasa: string,
  imc: string,
  fecha_creacion: Date,
  fecha_modificacion: Date,
  estado: string,
  usuario_modificacion: string,
  meta: string,
  bicep_izquierdo: string,
  bicep_derecho: string,
  cadera: string,
  cintura: string,
  muslo_derecho: string,
  muslo_izquierdo: string,
}
